name: bed_analysis
channels:
  - pytorch
  - nvidia
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch=2.6.0
  - pytorch-cuda=12.4
  - numpy>=2.1
  - pandas>=2.2
  - scipy>=1.15
  - scikit-learn>=1.6
  - statsmodels
  - py2bit>=0.3.3
  - pysam>=0.23.0
  - tqdm
  - matplotlib>=3.10
  - seaborn>=0.13
  - adjusttext
  - joblib
  - psutil
